import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
// import SearchBar from "@/components/SearchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SEFORA - Cosmetic Store",
  description: "SEFORA Cosmetic Store Online    Generated by Engineering: Seif El-Din Mostafa   ",
   icons: {
    icon: '/lip.svg',
  },
  keywords: "cosmetic, store, online, shopping, beauty, products",
  authors: [{ name: "Seif El-Din Mostafa", url: "01277379678" }],
  creator: "Seif El-Din Mostafa",
  openGraph: {
    title: "Cosmetic Store",
    description: "Cosmetic Store Online    Generated by Engineering: Seif El-Din Mostafa ",
    url: "https://cosmetic-store.com",
    siteName: "Cosmetic Store",

}
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        
        {children}
        <div className="container mx-auto px-4 bg-gray-50 text-gray-800 py-6 mt-10 text-center">
      🌸 موقعنا في طور التطوير المذهل
تابعونا الآن لأحدث صيحات الجمال والمكياج الفاخر. كل يوم جديد يأتيكم بمنتجات رائعة!

💄 للطلبات والاستفسارات:
📱 واتساب: 201108930939
✨ خدمة توصيل سريعة | دفع آمن عند الاستلام
        </div>
        <Footer />
      </body>
    </html>
  );
}
